server: 
  port: 8888        
spring:
  application:
    name: config-server
  cloud:
    config: 
      server: 
        git: 
          searchPaths: respo
          uri: https://github.com/forezp/SpringcloudConfig/
          username:    
          password:    
      label: master  
 
          
          



