# 设置基础镜像
FROM openjdk:8-jdk-alpine
# 挂载了tmp文件夹
VOLUME /tmp
# 复制文件
ADD serice-feign-0.0.1-SNAPSHOT.jar app.jar
# 暴露端口
EXPOSE 8765
# 启动程序
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]