server:
  port: 8761
eureka:
  client: 
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: 127.0.0.1
    #serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eurka-server

