server: 
  port: 8888        
spring:
  application:
    name: config-server
  cloud:
    config: 
      server: 
        git: 
          searchPaths: respo
          uri: https://gitee.com/linyang520/Springcloud.git
          username: 
          password: 
      label: master  
 
          
          



