server: 
  port: 8888        
spring:
  application:
    name: config-server
  cloud:
    config: 
      server: 
        git: 
          searchPaths: respo
          uri: http://gitlab.centaline.com.cn/dg-group/study.git
          username: linhd2   
          password: dg.1212
      label: master  
 
          
          



